{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apache-httpd-modsecurity.serviceAccountName" . }}
  labels:
{{ include "apache-httpd-modsecurity.labels" . | indent 4 }}
{{- end -}}
