name: Trigger builds on quay.io
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * MON'  # Run every Monday
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - crs-v3.3.2-waf1

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: HTTP POST quay.io
      # You may pin to the exact commit or the version.
      # uses: fjogeleit/http-request-action@3634ea0063747172ea475d8dafb6596eab2a1e11
      uses: fjogeleit/http-request-action@v1.4.1
      with:
        # Request URL
        url: https://quay.io/api/v1/repository/puzzle/apache-httpd-modsecurity/build/
        # Request Method
        method: POST
        # Content Type
        contentType: application/json
        # Request Body as JSON String
        data: '{"archive_url": "https://github.com/puzzle/apache-httpd-modsecurity/archive/${{ matrix.tag }}.tar.gz", "docker_tags": [ "${{ matrix.tag }}" ], "context": "/apache-httpd-modsecurity-${{ matrix.tag }}/", "dockerfile_path": "/apache-httpd-modsecurity-${{ matrix.tag }}/Dockerfile"}'
        # Bearer Authentication Token
        bearerToken: '${{ secrets.QUAY_ACCESS_TOKEN }}'
        # Prevent this Action to fail if the request respond without an response
        preventFailureOnNoResponse: # optional
